### PR TITLE
Update lib-utils version post npm publish

### PR DESCRIPTION
**Pull request by vojtechszocs**

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
Thanks for this release.

**Comment by florkbr** [comment]
@vojtechszocs I think we're running into worker image issues again 🙄 

```Checksums matched!
$>./configure --prefix=/go/.nvm/versions/node/v18.18.0 <
./configure: line 8: exec: python: not found
nvm: install v18.18.0 failed!
error: build error: building at STEP "RUN git clone -b $NVM_VERSION --depth 1 https://github.com/nvm-sh/nvm.git $NVM_DIR &&     . $NVM_DIR/nvm.sh &&     nvm install $NODE_VERSION &&     npm install -g npm@$NPM_VERSION": while running runtime: exit status 1
[36mINFO[0m[2023-10-26T19:51:53Z] Ran for 0s                                   
[31mERRO[0m[2023-10-26T19:51:53Z] Some steps failed:                           
[31mERRO[0m[2023-10-26T19:51:53Z] 
  * could not run steps: step root failed: error occurred handling build root-amd64: the build root-amd64 failed after 11m21s with reason DockerBuildFailed: Dockerfile build strategy has failed.```

**Pull request merged**
