### PR TITLE
Revert "Add ListView test coverage"

### PR DESCRIPTION
**Pull request by kdoberst**
This reverts commit 897ead8976dab8232bdd737f8750324aed3d0877.

There are numerous typescript changes that are causing failures in HAC-Infra preventing work in that repo from moving forward. 

This PR is preventing urgent work in HAC-Infra

### CODE REVIEW

**Comment by kdoberst** [comment]
The issue was on this line in HAC Infra :https://github.com/openshift/hac-infra/blob/main/src/components/WorkspaceList/WorkspaceList.tsx#L83

Screenshot of typescript error:
Screen Shot 2022-10-21 at 3 04 34 PM



Note that there wasn't an error until the latest version(utils

**Comment by florkbr** [comment]
I'm going to merge as this is blocking workspace development. We will need to re-deliver and coordinate/prioritize any type changes required in hac-infra with that team.

**Comment by florkbr** [comment]
@fhlavac FYI

**Pull request merged**
