### PR TITLE
Prepare to publish new package versions

### PR DESCRIPTION
**Pull request by vojtechszocs**
- `@openshift/dynamic-plugin-sdk` 4.0.0 :arrow_right: 5.0.0 (see changelog for details)
- `@openshift/dynamic-plugin-sdk-extensions` 1.3.0 :arrow_right: 1.4.0 (due to change in `peerDependencies`)
- `@openshift/dynamic-plugin-sdk-utils` 4.0.1 :arrow_right: 4.1.0 (due to change in `peerDependencies`)
- `@openshift/dynamic-plugin-sdk-webpack` 3.0.1 :arrow_right: 4.0.0 (see changelog for details)

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]

**Review by Hyperkid123 — APPROVED** [review]

**Review by fhlavac — APPROVED** [review]

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
