### PR TITLE
Add dynamic plugins overview documentation

### PR DESCRIPTION
**Pull request by vojtechszocs**
Added a general overview of dynamic plugin concepts without going into the underlying technical details.

### CODE REVIEW

**Review by andrewballantyne — COMMENTED** [review]
Looks good from a high level intro into what the SDK provides and how that relates the various layers.

LGTM. What's the next steps to growing the documentation? Extension definitions or plugin examples, anything like that?

**Comment by vojtechszocs** [comment]
After discussing with @andrewballantyne I will add some diagrams for more clarity.

**Comment by vojtechszocs** [comment]
> What's the next steps to growing the documentation? Extension definitions or plugin examples, anything like that?

The next step is to update READMEs of essential lib packages, notably `lib-core` and `lib-webpack` to provide users with specific build & runtime plugin documentation.

**Review by andrewballantyne — APPROVED** [review]
Awesome, great graphics. I think it helps tell the story of the SDK much better. Thanks for the updates!

**Comment by andrewballantyne** [comment]
/hold

Not sure if you're looking for another reviewer.

**Review by florkbr — APPROVED** [review]

**Pull request merged**
