### PR TITLE
Revert "Merge pull request #173 from kdoberst/main"

### PR DESCRIPTION
**Pull request by florkbr**
This reverts commit ef75898d4c6880295bee559ed162cc13ff20cacf, reversing changes made to 59bf5bff814d78a6ad25212570d55c2423fd3678.

### CODE REVIEW

**Comment by florkbr** [comment]
Looking into TS failures in hac-infra

**Comment by kdoberst** [comment]
Tested locally building lib-utils and loading it in HAC-Infra.   Works great.  Great job figuring this out!

**Comment by fhlavac** [comment]
Thank you @florkbr !

**Pull request merged**
