### PR TITLE
Use React router v6

### PR DESCRIPTION
**Pull request by fhlavac**
Updated `react-router` to v6

@vidyanambiar @florkbr

### CODE REVIEW

**Review by karelhala — COMMENTED** [review]
Looking good! Haven't tested this in any UI, so I'll defer the merge to @florkbr

**Comment by vidyanambiar** [comment]
Thanks, Filip! Looks good to me. I was able to render the table in a test branch on hac-infra using the changes from this PR. I'll defer the merge to Bryan.

**Pull request merged**
